config/routes.rb
Rails.application.routes.draw do
  resources :categories

  resources :lessons

  resources :courses

  devise_for :users
  get 'site/about', path: "about"

  get 'site/contact'

  get 'site/index', path: "home"

  get 'site/show'

  root 'site#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :courses
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :category
  has_many :lessons
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :course
  belongs_to :user
  mount_uploader :image, ImageUploader
 	include PgSearch

	pg_search_scope :search, against: [:name, :description],
	using: {tsearch: {dictionary: "english"}}

  def self.text_search(query)
  	if query.present?
  		search(query)
  	end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :lessons
         include Gravtastic
		 gravtastic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :category_id)
    end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.js
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:name, :image, :video, :duration, :description, :course_id, :user_id)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def about
  end

  def contact
  end

  def index
  	qry = params[:query]
  	if qry.to_s == ''
		  @les = Lesson.all.paginate(:page => params[:page], per_page: 6)
  	else
		  @les = Lesson.text_search(qry).paginate(:page => params[:page], per_page: 12)
  	end
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/categories/_form.html.haml
= form_for @category, :html => { :class => "form-horizontal" } do |f|
  -if @category.errors.any?
    .alert.alert-danger.alert-dismissable
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      %h4= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"

      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name, :class => 'col-sm-1 control-label'
    .col-sm-8
      = f.text_field :name, :class => 'form-control'
  .form-group
    .col-sm-offset-1.col-sm-10
      = f.submit :class => 'btn btn-primary'

app/views/categories/edit.html.haml
.page-header
  = link_to categories_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @category, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing category

= render 'form'

app/views/categories/index.html.haml
.page-header
  = link_to new_category_path, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus

.table.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Name
        %th
        %th
        %th

    %tbody
      - @categories.each do |category|
        %tr
          %td= category.name
          %td= link_to 'Show', category
          %td= link_to 'Edit', edit_category_path(category)
          %td= link_to 'Destroy', category, :data => { confirm: 'Are you sure?' }, :method => :delete

app/views/categories/new.html.haml
.page-header
  = link_to categories_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back

= render 'form'

app/views/categories/show.html.haml
.page-header
  = link_to categories_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_category_path(@category), :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit

%dl.dl-horizontal
  %dt Name:
  %dd= @category.name

app/views/courses/_form.html.haml
= form_for @course, :html => { :class => "form-horizontal" } do |f|
  -if @course.errors.any?
    .alert.alert-danger.alert-dismissable
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      %h4= "#{pluralize(@course.errors.count, "error")} prohibited this course from being saved:"

      %ul
        - @course.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name, :class => 'col-sm-1 control-label'
    .col-sm-10
      = f.text_field :name, :class => 'form-control'
  .form-group
    = f.label :category, :class => 'col-sm-1 control-label'
    .col-sm-10
      = f.select :category_id, Category.all.map { |c| [c.name, c.id]}
  .form-group
    .col-sm-offset-1.col-sm-10
      = f.submit :class => 'btn btn-primary'

app/views/courses/edit.html.haml
.page-header
  = link_to courses_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @course, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing course

= render 'form'

app/views/courses/index.html.haml
.page-header
  = link_to new_course_path, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus


.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Name
        %th Category
        %th
        %th
        %th

    %tbody
      - @courses.each do |course|
        %tr
          %td= course.name
          %td= course.category.name
          %td= link_to 'Show', course
          %td= link_to 'Edit', edit_course_path(course)
          %td= link_to 'Destroy', course, :data => { confirm: 'Are you sure?' }, :method => :delete

app/views/courses/new.html.haml
.page-header
  = link_to courses_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back

= render 'form'

app/views/courses/show.html.haml
.page-header
  = link_to courses_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_course_path(@course), :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit

%dl.dl-horizontal
  %dt Name:
  %dd= @course.name
  %dt Category:
  %dd= @course.category

app/views/layouts/_footer.html.erb
 <div class="refoliobuttonwrap ref-tools-full" style="bottom: 0px;padding-bottom:10px;z-index:999;">
          <div class="refolio_pagination">
            <%= will_paginate @les,class: "page button" %>
          </div>
          <%= link_to "Mobile", root_path, class: "refoliobutton",style: "opacity: 1" %>
          <%= link_to "Web Programing", root_path, class: "refoliobutton",style: "opacity: 1" %>
          <%= link_to "Desktop", root_path, class: "refoliobutton",style: "opacity: 1" %>
          <%= link_to "Network", root_path, class: "refoliobutton",style: "opacity: 1" %>
            <div class="refoliosizes">
           
            </div>
            <span class="fa fa-arrow-circle-down toggle-tools"></span>
            <div class="ref-sorts">
              <span class="sortbyrating icon-star6"></span>
              <span class="sortbydate icon-calendar4"></span>
              <span class="sortbycomments icon-bubbles2"></span>
            </div>
      </div>




<script type="text/javascript">
$(function(){
  $('.toggle-tools').on('click', function(){
        $('.refoliobuttonwrap').toggleClass('ref-tools-full');

 });


  $('.mCSB_container .topnav li').on('click', function(){
            $('.isactive').removeClass('isactive');
            $(this).addClass('isactive');
        });

});
</script>

app/views/layouts/_header.html.erb
<div id="stm-menu">
    <span class="fa fa-align-center stm-close" style="top:3px;"></span>
    <div class="scroll-cont mCustomScrollbar _mCS_1" style="height: 90%;">
        <div class="mCustomScrollBox mCS-dark-thin" id="mCSB_1" style="position:relative; height:100%; overflow:hidden; max-width:100%;">

            <div class="mCSB_container">
                <ul class="topnav">
                    <li id="stm-ebook" class="isactive">
                        <%= link_to '<span class="fa fa-home" style="font-size:17px;width:20px;"></span> hOme'.html_safe, root_path, class: "stm-nav-item" %>
                    </li>
                    <li id="stm-weg" class="">
                        <%= link_to '<span class="fa fa-lightbulb-o" style="font-size:18px;width:20px;"></span> cOurse'.html_safe, site_contact_path, class: "stm-nav-item" %>
                    </li>
                    <li id="stm-World" class="">
                        <%= link_to '<span class="fa fa-envelope-o" style="font-size:15px;width:20px;"></span> aBout'.html_safe, site_about_path, class: "stm-nav-item" %>
                    </li>
                    <% if user_signed_in? %>
                        <li>
                        <%= link_to '<span class="fa fa-sign-out" style="font-size:17px;width:20px;"></span> lOg Out'.html_safe, destroy_user_session_path, method: :delete, style: "text-align:center;" %>
                        </li>
                             <span class="control-image">
                            <%= image_tag current_user.gravatar_url,style: "border-radius:100px;margin-top:5px;display:flex;align-items:center;" %>
                            </span>
                            

                    <% else %>
                    <li id="stm-grill" class="">
                        <%= link_to '<span class="fa fa-lock" style="font-size:17px;width:20px;"></span> lOgin'.html_safe, user_session_path, class: "stm-nav-item" %>
                    </li>
                    <% end %>
                </ul>
            </div>
            <% if user_signed_in? %>
            <% else %>
            
            <% end %>

            <div class="mCSB_scrollTools" style="position: absolute; display: block;">
                <a class="mCSB_buttonUp" oncontextmenu="return false;"></a>
                <div class="mCSB_draggerContainer">
                    <div class="mCSB_dragger" style="position: absolute; top: 0px; height: 193px;" oncontextmenu="return false;">
                        <div class="mCSB_dragger_bar" style="position: relative; line-height: 193px;"></div>
                    </div>
                    <div class="mCSB_draggerRail"></div>
                </div>
            <a class="mCSB_buttonDown" oncontextmenu="return false;"></a>
            </div>
        </div>

    </div>
</div>





    <script type="text/javascript">
        $(function () {
            $("input").iCheck({
                checkboxClass: 'icheckbox_square-blue',
                increaseArea: '20%' // optional
            });
            $(".dark input").iCheck({
                checkboxClass: 'icheckbox_polaris',
                increaseArea: '20%' // optional
            });
            $(".form-control").focus(function () {
                $(this).closest(".textbox-wrap").addClass("focused");
            }).blur(function () {
                $(this).closest(".textbox-wrap").removeClass("focused");
            });

            //On Scroll Animations


            if ($(window).width() >= 968 && !Modernizr.touch && Modernizr.cssanimations) {

                $("body").addClass("scroll-animations-activated");
                $('[data-animation-delay]').each(function () {
                    var animationDelay = $(this).data("animation-delay");
                    $(this).css({
                        "-webkit-animation-delay": animationDelay,
                        "-moz-animation-delay": animationDelay,
                        "-o-animation-delay": animationDelay,
                        "-ms-animation-delay": animationDelay,
                        "animation-delay": animationDelay
                    });

                });
                $('[data-animation]').waypoint(function (direction) {
                    if (direction == "down") {
                        $(this).addClass("animated " + $(this).data("animation"));

                    }
                }, {
                    offset: '90%'
                }).waypoint(function (direction) {
                    if (direction == "up") {
                        $(this).removeClass("animated " + $(this).data("animation"));

                    }
                }, {
                    offset: $(window).height() + 1
                });
            }

            //End On Scroll Animations


            $(".main-nav a[href]").click(function () {
                var scrollElm = $(this).attr("href");

                $("html,body").animate({ scrollTop: $(scrollElm).offset().top }, 500);

                $(".main-nav a[href]").removeClass("active");
                $(this).addClass("active");
            });




            if ($(window).width() > 1000 && !Modernizr.touch) {
                var options = {
                    $menu: ".main-nav",
                    menuSelector: 'a',
                    panelSelector: 'section',
                    namespace: '.panelSnap',
                    onSnapStart: function () { },
                    onSnapFinish: function ($target) {
                        $target.find('input:first').focus();
                    },
                    directionThreshold: 50,
                    slideSpeed: 200
                };
                $('body').panelSnap(options);

            }

            $(".colorBg a[href]").click(function () {
                var scrollElm = $(this).attr("href");

                $("html,body").animate({ scrollTop: $(scrollElm).offset().top }, 500);

                return false;
            });


           

        });
    </script>

app/views/layouts/_msg.html.erb
	<% flash.each do |name, msg| %>
	  <% if msg.is_a?(String) %>
	    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
	      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	      <%= content_tag :div, msg, :id => "flash_#{name}" %>
	    </div>
	  <% end %>
	<% end %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %title Starter Template for Bootstrap
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no", :name => "viewport"}
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}

    / Le HTML5 shim, for IE6-8 support of HTML5 elements
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body

    = render "layouts/header"
      
    .container_wrap
      = render "layouts/msg"
      = yield
    / = render "layouts/footer"
    //  .menu-search
    /   = form_tag root_path, method: :get do
    /     %p
    /       = submit_tag "Search", name: nil
    /       = text_field_tag :query, params[:query]

app/views/lessons/_form.html.haml
= form_for @lesson, :html => { :class => "form-horizontal" } do |f|
  -if @lesson.errors.any?
    .alert.alert-danger.alert-dismissable
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      %h4= "#{pluralize(@lesson.errors.count, "error")} prohibited this lesson from being saved:"

      %ul
        - @lesson.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name, :class => 'col-sm-1 control-label'
    .col-sm-10
      = f.text_field :name, :class => 'form-control'
  .form-group
    = f.label :image, :class => 'col-sm-1 control-label'
    .col-sm-10
      = f.file_field :image
  .form-group
    = f.label :video, :class => 'col-sm-1 control-label'
    .col-sm-10
      = f.text_field :video, :class => 'form-control'
  .form-group
    = f.label :duration, :class => 'col-sm-1 control-label'
    .col-sm-10
      = f.text_field :duration, :class => 'form-control'
  .form-group
    = f.label :description, :class => 'col-sm-1 control-label'
    .col-sm-10
      = f.text_area :description, :class => 'form-control'
  .form-group
    = f.label :course, :class => 'col-sm-1 control-label'
    .col-sm-10
      = f.select :course_id, Course.all.map {|c| [c.name, c.id]}

  .form-group
    .col-sm-offset-1.col-sm-10
      = f.submit :class => 'btn btn-primary'

app/views/lessons/edit.html.haml
.page-header
  = link_to lessons_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @lesson, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing lesson

= render 'form'

app/views/lessons/index.html.haml
.page-header
  = link_to new_lesson_path, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Name
        %th Image
        %th Video
        %th Duration
        %th Description
        %th Course
        %th
        %th
        %th

    %tbody
      - @lessons.each do |lesson|
        %tr
          %td= lesson.name
          %td= lesson.image
          %td= lesson.video
          %td= lesson.duration
          %td= lesson.description
          %td= lesson.course.name
          %td= link_to 'Show', lesson
          %td= link_to 'Edit', edit_lesson_path(lesson)
          %td= link_to 'Destroy', lesson, :data => { confirm: 'Are you sure?' }, :method => :delete

app/views/lessons/new.html.haml
.container

.page-header
  = link_to lessons_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back

= render 'form'

app/views/lessons/show.html.haml
.page-header
  = link_to lessons_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_lesson_path(@lesson), :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit


%dl.dl-horizontal
  %dt Name:
  %dd= @lesson.name
  %dt Image:
  %dd= @lesson.image
  %dt Video:
  %dd= @lesson.video
  %dt Duration:
  %dd= @lesson.duration
  %dt Description:
  %dd= @lesson.description
  %dt Course:
  %dd= @lesson.course
  %dt User:
  %dd= @lesson.user

app/views/site/_lessons.html.erb
                <div class="pribox">
                    <% @les.each do |l| %>
                        <!-- start li container each post returned-->
                        <div class="refolioimg refolioimage logos isotope-item" id="demo1" style="transform: translate3d(0px, 0px, 0px);display:inline-block;">
                                            <!-- refolio img wrap-->
                            <div class="refolioimgwrap" style="background:url(<%= image_path(l.image)%>);width=70%; height=200px;display:inline-block;">
                            </div>                             

                            <div class="refoliosumm">
                                <h2><%= link_to truncate(l.name, length:20, class: "green") %></h2>
                                <hr style="width:80%; margin-left:10%;">
                                <p><%= truncate(l.description, length: 130) %></p>
                            </div>
                                <div class="refolio-share-buttons">
                                    <!-- Facebook -->
                                    <a href="http://www.facebook.com/sharer.php?u=http://www.nuvuthemes.com/ovogallery/yacht-store/" target="_blank" class="ref-facebook"><span class="icon-facebook"></span></a>

                                    <span class="icon-facebook"></span>
                                    <%= link_to '<span class="icon-facebook"></span>'.html_safe, root_path, class: "ref-facebook" %>

                                    <!-- Twitter -->
                                    <a href="http://twitter.com/share?url=http://www.nuvuthemes.com/ovogallery/yacht-store/&amp;text=Yacht%20Store" target="_blank" class="ref-twitter"><span class="icon-twitter"></span></a>

                                    <!-- Google+ -->
                                    <a href="https://plus.google.com/share?url=http://www.nuvuthemes.com/ovogallery/yacht-store/" target="_blank" class="ref-google"><span class="icon-googleplus"></span></a>
                                </div>
                        </div>
                    <% end %>
                </div> <!-- end refoliogallery -->

app/views/site/contact.html.erb
<div id="page" class="hfeed site">
		<header id="masthead" class="site-header" role="banner">
			<div id="navbar" class="navbar">
				<nav id="site-navigation" class="navigation main-navigation" role="navigation">
					<h3 class="menu-toggle">Menu</h3>
					<div class="menu-menu-2-container"><ul id="menu-menu-2" class="nav-menu">
<li id="menu-item-62" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-62"><a href="http://nuvuthemes.com/shop/woozoom/">Download</a></li>
<li id="menu-item-66" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-66"><a href="../../index.html">Shop</a></li>
<li id="menu-item-81" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-81"><a href="../product/video-links-demo/index.html">WooCommerce Video Links</a></li>
<li id="menu-item-268" class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-262 current_page_item menu-item-268"><a href="index.html">Wah-Menu</a></li>
<li id="menu-item-402" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-402"><a href="../articlescroll/index.html">ArticleScroll</a></li>
</ul></div>				
<form role="search" method="get" class="search-form" action="http://www.nuvuthemes.com/woozoom/">
				<label>
					<span class="screen-reader-text">Search for:</span>
					<input type="search" class="search-field" placeholder="Search …" value="" name="s" title="Search for:">
				</label>
			</form>		
</nav><!-- #site-navigation -->
			</div><!-- #navbar -->
		</header><!-- #masthead -->

</div>

app/views/site/index.html.erb
 <div class="fullsize">
      <div class="menu-search">
          <form class="navbar-form" role="search"> 
                <div class="form-group">
                  <div class="input-group">
                  <%= form_tag root_path, method: :get, :id => "lesson_search" do %>
      <%= text_field_tag :query, params[:query], class: "form-control input-sm no-border rounded", placeholder: "Searching...." %>
                  <% end %>
                  </div>
                </div>
          </form> 
      </div>
      <div id="lesson">
        <%= render 'lessons' %>                   
      </div>
</div><!--end container-->



<%= render "layouts/footer" %>


   <script type="text/javascript">
                          var jQuery = jQuery.noConflict();
                          jQuery(document).ready(function(){

                          //set width and heights based on dynamic sizes
                          });
                      </script>
                      <style>
                          .refolioimg{
                            width:335px!important;
                           height:272px!important;

                          }
                          .refolioimg.ref-small{
                            width:200px!important;
                           height:190px!important;

                          }
                          .refolioimg.ref-medium{
                            width:335px!important;
                           height:272px!important;

                          }
                          .refolioimg.ref-large{
                            width:400px!important;
                           height:340px!important;

                          }
                          .ref-active {
                              z-index:9999!important;
                             margin-top:-70px!important;
                             width:375px!important;
                              margin-left:-20px!important;
                                height:670px!important;
                              }
                          .ref-active.ref-small {
                              z-index:9999!important;
                             margin-top:-70px!important;
                             width:240px!important;
                              margin-left:-20px!important;
                                height:400px!important;
                              }
                              .ref-active.ref-medium {
                              z-index:9999!important;
                             margin-top:-70px!important;
                             width:375px!important;
                              margin-left:-20px!important;
                                height:670px!important;
                              }
                              .ref-active.ref-large {
                              z-index:9999!important;
                             margin-top:-70px!important;
                             width:440px!important;
                              margin-left:-20px!important;
                                height:800px!important;
                              }
                           .refvotes{

                           }
                      </style>

app/views/site/index.js.erb
$("#lessons").html("<%= escape_javascript(render("lessons"))%> ");

app/views/site/show.html.erb
<h1>Site#show</h1>
<p>Find me in app/views/site/show.html.erb</p>